// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGAD.Infrastructure.Persistence;

#nullable disable

namespace SIGAD.Infrastructure.Migrations
{
    [DbContext(typeof(SigadDbContext))]
    [Migration("20250603171613_SeedRangosDataStatic")]
    partial class SeedRangosDataStatic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIGAD.Domain.Entities.Rango", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Rangos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1a75764-3420-4e00-91c0-66917c0d3e6f"),
                            Descripcion = "Profesor de Tiempo Completo en categoría Auxiliar.",
                            Nombre = "Profesor Auxiliar TC"
                        },
                        new
                        {
                            Id = new Guid("d2b86889-81b2-4a3a-984e-127424d349af"),
                            Descripcion = "Profesor de Tiempo Completo en categoría Asistente.",
                            Nombre = "Profesor Asistente TC"
                        },
                        new
                        {
                            Id = new Guid("e3c97990-92c3-5b4b-a95f-238535e450b0"),
                            Descripcion = "Profesor de Tiempo Completo en categoría Asociado.",
                            Nombre = "Profesor Asociado TC"
                        },
                        new
                        {
                            Id = new Guid("f4d08aa1-a3d4-6c5c-ba60-349646f561c1"),
                            Descripcion = "Profesor de Tiempo Completo en categoría Titular.",
                            Nombre = "Profesor Titular TC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
