// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGAD.Infrastructure.Persistence;

#nullable disable

namespace SIGAD.Infrastructure.Migrations
{
    [DbContext(typeof(SigadDbContext))]
    [Migration("20250707020005_hola")]
    partial class hola
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIGAD.Domain.Entities.AccionesDePersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CertificadoRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenidoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DocumentoRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoCargo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocenteCedula");

                    b.ToTable("AccionesDePersonal");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.AccionesDePersonalPorSolicitud", b =>
                {
                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccionDePersonalId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudId", "AccionDePersonalId");

                    b.HasIndex("AccionDePersonalId");

                    b.ToTable("AccionesDePersonalPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Apelacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aceptada")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentosRespaldo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaLimiteRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPresentacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ObservacionesComision")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SolicitudAscensoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudAscensoId");

                    b.ToTable("Apelaciones");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Articulo", b =>
                {
                    b.Property<string>("DOI")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("ArchivoRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenidoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("EsIndexado")
                        .HasColumnType("bit");

                    b.Property<bool>("EsVerificado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdiomaPublicacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObservacionesVerificacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Revista")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnidadVerificadora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlCloudinary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DOI");

                    b.HasIndex("DocenteCedula");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.ArticulosPorSolicitud", b =>
                {
                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArticuloDOI")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SolicitudId", "ArticuloDOI");

                    b.HasIndex("ArticuloDOI");

                    b.ToTable("ArticulosPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Cuenta", b =>
                {
                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CodigoExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("CodigoRecuperacion")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Correo");

                    b.HasIndex("DocenteCedula")
                        .IsUnique();

                    b.ToTable("Cuentas", t =>
                        {
                            t.HasCheckConstraint("CK_Cuentas_Rol", "Rol IN ('ADMINISTRADOR', 'DOCENTE')");
                        });
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificadoRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenidoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HorasImpartidas")
                        .HasColumnType("int");

                    b.Property<bool>("ImpartidoPorDocente")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroHoras")
                        .HasColumnType("int");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoCurso")
                        .HasColumnType("int");

                    b.Property<string>("UrlCloudinary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteCedula");

                    b.HasIndex("OrganizacionId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.CursosPorSolicitud", b =>
                {
                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudId", "CursoId");

                    b.HasIndex("CursoId");

                    b.ToTable("CursosPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Docente", b =>
                {
                    b.Property<string>("Cedula")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RangoActualId")
                        .HasColumnType("int");

                    b.HasKey("Cedula");

                    b.HasIndex("RangoActualId");

                    b.ToTable("Docentes");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.EvaluacionDocente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("InformeRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodoAcademico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PuntajePorcentual")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("UrlCloudinary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteCedula");

                    b.ToTable("EvaluacionesDocentes");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.EvaluacionesPorSolicitud", b =>
                {
                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudId", "EvaluacionId");

                    b.HasIndex("EvaluacionId");

                    b.ToTable("EvaluacionesPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.ExperienciaLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CertificadoRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenidoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<string>("UrlCloudinary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteCedula");

                    b.HasIndex("OrganizacionId");

                    b.ToTable("ExperienciasLaborales");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.ExperienciaPorSolicitud", b =>
                {
                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExperienciaId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudId", "ExperienciaId");

                    b.HasIndex("ExperienciaId");

                    b.ToTable("ExperienciasPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Investigacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("EsInternacional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("InformeRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MesesDeInvestigacion")
                        .HasColumnType("int");

                    b.Property<int>("MesesDeParticipacion")
                        .HasColumnType("int");

                    b.Property<string>("RolEnInvestigacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TipoProyecto")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UnidadVerificadora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlCloudinary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteCedula");

                    b.ToTable("Investigaciones");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.InvestigacionesPorSolicitud", b =>
                {
                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InvestigacionId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudId", "InvestigacionId");

                    b.HasIndex("InvestigacionId");

                    b.ToTable("InvestigacionesPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("EsLeida")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLeida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UrlRedireccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteCedula");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Organizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoOrganizacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Organizaciones");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Rango", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AniosExperienciaRequeridos")
                        .HasColumnType("int");

                    b.Property<int>("ArticulosRequeridos")
                        .HasColumnType("int");

                    b.Property<int>("HorasCapacitacionImpartidaRequeridas")
                        .HasColumnType("int");

                    b.Property<int>("HorasCapacitacionPedagogicaRequeridas")
                        .HasColumnType("int");

                    b.Property<int>("HorasCursoRequeridas")
                        .HasColumnType("int");

                    b.Property<int>("MesesInvestigacionRequeridos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("PermiteCoordinacionProyectos")
                        .HasColumnType("bit");

                    b.Property<int>("ProyectosInternacionalesRequeridos")
                        .HasColumnType("int");

                    b.Property<int>("PublicacionesIdiomaExtranjeroRequeridas")
                        .HasColumnType("int");

                    b.Property<decimal>("PuntajePromedioEvaluacionesRequerido")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("RequiereArticuloEnGradoActual")
                        .HasColumnType("bit");

                    b.Property<int>("TesisDirigidasRequeridas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Rangos");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.SolicitudAscenso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AceptacionODemanda")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("AprobadoPorComision")
                        .HasColumnType("bit");

                    b.Property<bool>("AprobadoPorConsejo")
                        .HasColumnType("bit");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("FechaAprobacionComision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAprobacionConsejo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteApelacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNotificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucionApelacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NotificacionEnviada")
                        .HasColumnType("bit");

                    b.Property<string>("ObservacionesAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesComision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesConsejo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RangoActualId")
                        .HasColumnType("int");

                    b.Property<int>("RangoSolicitadoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoResolucion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteCedula");

                    b.HasIndex("RangoActualId");

                    b.HasIndex("RangoSolicitadoId");

                    b.ToTable("SolicitudesAscenso", null, t =>
                        {
                            t.HasCheckConstraint("CK_SolicitudesAscenso_Estado", "Estado IN ('Borrador', 'Enviada', 'En Revision', 'Aprobada', 'Rechazada', 'En Apelacion', 'Rechazada Definitiva', 'Aprobada Por Apelacion', 'Cerrada Sin Respuesta')");
                        });
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.TesisDirigida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificacionRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenidoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NivelAcademico")
                        .HasColumnType("int");

                    b.Property<string>("TituloTesis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UrlCloudinary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteCedula");

                    b.ToTable("TesisDirigidas");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.TesisPorSolicitud", b =>
                {
                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TesisId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudId", "TesisId");

                    b.HasIndex("TesisId");

                    b.ToTable("TesisPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.AccionesDePersonal", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("AccionesDePersonal")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.AccionesDePersonalPorSolicitud", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.AccionesDePersonal", "AccionDePersonal")
                        .WithMany("AccionesDePersonalPorSolicitud")
                        .HasForeignKey("AccionDePersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.SolicitudAscenso", "SolicitudAscenso")
                        .WithMany("AccionesDePersonalPorSolicitud")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccionDePersonal");

                    b.Navigation("SolicitudAscenso");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Apelacion", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.SolicitudAscenso", "SolicitudAscenso")
                        .WithMany("Apelaciones")
                        .HasForeignKey("SolicitudAscensoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitudAscenso");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Articulo", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("Articulos")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.ArticulosPorSolicitud", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Articulo", "Articulo")
                        .WithMany("ArticulosPorSolicitud")
                        .HasForeignKey("ArticuloDOI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.SolicitudAscenso", "SolicitudAscenso")
                        .WithMany("ArticulosPorSolicitud")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("SolicitudAscenso");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Cuenta", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithOne("Cuenta")
                        .HasForeignKey("SIGAD.Domain.Entities.Cuenta", "DocenteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Curso", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("Cursos")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany("Cursos")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.CursosPorSolicitud", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Curso", "Curso")
                        .WithMany("CursosPorSolicitud")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.SolicitudAscenso", "SolicitudAscenso")
                        .WithMany("CursosPorSolicitud")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("SolicitudAscenso");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Docente", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Rango", "RangoActual")
                        .WithMany()
                        .HasForeignKey("RangoActualId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RangoActual");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.EvaluacionDocente", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.EvaluacionesPorSolicitud", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.EvaluacionDocente", "Evaluacion")
                        .WithMany("EvaluacionesPorSolicitud")
                        .HasForeignKey("EvaluacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.SolicitudAscenso", "Solicitud")
                        .WithMany("EvaluacionesPorSolicitud")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluacion");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.ExperienciaLaboral", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("ExperienciasLaborales")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany("ExperienciasLaborales")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.ExperienciaPorSolicitud", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.ExperienciaLaboral", "ExperienciaLaboral")
                        .WithMany("ExperienciasPorSolicitud")
                        .HasForeignKey("ExperienciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.SolicitudAscenso", "SolicitudAscenso")
                        .WithMany("ExperienciaPorSolicitud")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperienciaLaboral");

                    b.Navigation("SolicitudAscenso");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Investigacion", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("Investigaciones")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.InvestigacionesPorSolicitud", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Investigacion", "Investigacion")
                        .WithMany("InvestigacionesPorSolicitud")
                        .HasForeignKey("InvestigacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.SolicitudAscenso", "SolicitudAscenso")
                        .WithMany("InvestigacionesPorSolicitud")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investigacion");

                    b.Navigation("SolicitudAscenso");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("Notificaciones")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.SolicitudAscenso", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("Solicitudes")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.Rango", "RangoActual")
                        .WithMany("SolicitudesComoRangoActual")
                        .HasForeignKey("RangoActualId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGAD.Domain.Entities.Rango", "RangoSolicitado")
                        .WithMany("SolicitudesComoRangoSolicitado")
                        .HasForeignKey("RangoSolicitadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("RangoActual");

                    b.Navigation("RangoSolicitado");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.TesisDirigida", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("TesisDirigidas")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.TesisPorSolicitud", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.SolicitudAscenso", "SolicitudAscenso")
                        .WithMany("TesisPorSolicitud")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.TesisDirigida", "TesisDirigida")
                        .WithMany("TesisPorSolicitud")
                        .HasForeignKey("TesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitudAscenso");

                    b.Navigation("TesisDirigida");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.AccionesDePersonal", b =>
                {
                    b.Navigation("AccionesDePersonalPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Articulo", b =>
                {
                    b.Navigation("ArticulosPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Curso", b =>
                {
                    b.Navigation("CursosPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Docente", b =>
                {
                    b.Navigation("AccionesDePersonal");

                    b.Navigation("Articulos");

                    b.Navigation("Cuenta");

                    b.Navigation("Cursos");

                    b.Navigation("Evaluaciones");

                    b.Navigation("ExperienciasLaborales");

                    b.Navigation("Investigaciones");

                    b.Navigation("Notificaciones");

                    b.Navigation("Solicitudes");

                    b.Navigation("TesisDirigidas");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.EvaluacionDocente", b =>
                {
                    b.Navigation("EvaluacionesPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.ExperienciaLaboral", b =>
                {
                    b.Navigation("ExperienciasPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Investigacion", b =>
                {
                    b.Navigation("InvestigacionesPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Organizacion", b =>
                {
                    b.Navigation("Cursos");

                    b.Navigation("ExperienciasLaborales");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Rango", b =>
                {
                    b.Navigation("SolicitudesComoRangoActual");

                    b.Navigation("SolicitudesComoRangoSolicitado");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.SolicitudAscenso", b =>
                {
                    b.Navigation("AccionesDePersonalPorSolicitud");

                    b.Navigation("Apelaciones");

                    b.Navigation("ArticulosPorSolicitud");

                    b.Navigation("CursosPorSolicitud");

                    b.Navigation("EvaluacionesPorSolicitud");

                    b.Navigation("ExperienciaPorSolicitud");

                    b.Navigation("InvestigacionesPorSolicitud");

                    b.Navigation("TesisPorSolicitud");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.TesisDirigida", b =>
                {
                    b.Navigation("TesisPorSolicitud");
                });
#pragma warning restore 612, 618
        }
    }
}
