// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGAD.Infrastructure.Persistence;

#nullable disable

namespace SIGAD.Infrastructure.Migrations
{
    [DbContext(typeof(SigadDbContext))]
    partial class SigadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIGAD.Domain.Entities.Articulo", b =>
                {
                    b.Property<string>("DOI")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<string>("ArchivoRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenidoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Revista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DOI");

                    b.HasIndex("DocenteCedula");

                    b.ToTable("Articulos", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.ArticulosPorSolicitud", b =>
                {
                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArticuloDOI")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SolicitudAscensoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SolicitudId", "ArticuloDOI");

                    b.HasIndex("ArticuloDOI");

                    b.HasIndex("SolicitudAscensoId");

                    b.ToTable("ArticulosPorSolicitud", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Cuenta", b =>
                {
                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Correo");

                    b.HasIndex("DocenteCedula")
                        .IsUnique();

                    b.ToTable("Cuentas", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificadoRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenidoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroHoras")
                        .HasColumnType("int");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocenteCedula");

                    b.HasIndex("OrganizacionId");

                    b.ToTable("Cursos", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.CursosPorSolicitud", b =>
                {
                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<Guid>("SolicitudAscensoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SolicitudId", "CursoId");

                    b.HasIndex("CursoId");

                    b.HasIndex("SolicitudAscensoId");

                    b.ToTable("CursosPorSolicitud", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Docente", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cedula");

                    b.ToTable("Docentes", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.EvaluacionDocente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("InformeRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodoAcademico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PuntajePorcentual")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteCedula");

                    b.ToTable("EvaluacionesDocentes", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.EvaluacionesPorSolicitud", b =>
                {
                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EvaluacionId")
                        .HasColumnType("int");

                    b.Property<int>("EvaluacionDocenteId")
                        .HasColumnType("int");

                    b.Property<Guid>("SolicitudAscensoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SolicitudId", "EvaluacionId");

                    b.HasIndex("EvaluacionDocenteId");

                    b.HasIndex("SolicitudAscensoId");

                    b.ToTable("EvaluacionesPorSolicitud", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.ExperienciaLaboral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificadoRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContenidoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocenteCedula");

                    b.HasIndex("OrganizacionId");

                    b.ToTable("ExperienciasLaborales", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.ExperienciaPorSolicitud", b =>
                {
                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExperienciaId")
                        .HasColumnType("int");

                    b.Property<int>("ExperienciaLaboralId")
                        .HasColumnType("int");

                    b.Property<Guid>("SolicitudAscensoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SolicitudId", "ExperienciaId");

                    b.HasIndex("ExperienciaLaboralId");

                    b.HasIndex("SolicitudAscensoId");

                    b.ToTable("ExperienciaPorSolicitud", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Investigacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("InformeRuta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MesesDeInvestigacion")
                        .HasColumnType("int");

                    b.Property<string>("RolEnInvestigacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocenteCedula");

                    b.ToTable("Investigaciones", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.InvestigacionesPorSolicitud", b =>
                {
                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InvestigacionId")
                        .HasColumnType("int");

                    b.Property<Guid>("SolicitudAscensoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SolicitudId", "InvestigacionId");

                    b.HasIndex("InvestigacionId");

                    b.HasIndex("SolicitudAscensoId");

                    b.ToTable("InvestigacionesPorSolicitud", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Organizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoOrganizacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizaciones", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Rango", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AniosExperienciaRequeridos")
                        .HasColumnType("int");

                    b.Property<int>("ArticulosRequeridos")
                        .HasColumnType("int");

                    b.Property<int>("HorasCursoRequeridas")
                        .HasColumnType("int");

                    b.Property<int>("MesesInvestigacionRequeridos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PuntajePromedioEvaluacionesRequerido")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.ToTable("Rangos", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.SolicitudAscenso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocenteCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObservacionesAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RangoActualId")
                        .HasColumnType("int");

                    b.Property<int>("RangoSolicitadoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocenteCedula");

                    b.HasIndex("RangoActualId");

                    b.HasIndex("RangoSolicitadoId");

                    b.ToTable("SolicitudesAscenso", (string)null);
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Articulo", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("Articulos")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.ArticulosPorSolicitud", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloDOI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.SolicitudAscenso", "SolicitudAscenso")
                        .WithMany("ArticulosPorSolicitud")
                        .HasForeignKey("SolicitudAscensoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("SolicitudAscenso");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Cuenta", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithOne("Cuenta")
                        .HasForeignKey("SIGAD.Domain.Entities.Cuenta", "DocenteCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Curso", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("Cursos")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany("Cursos")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.CursosPorSolicitud", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.SolicitudAscenso", "SolicitudAscenso")
                        .WithMany("CursosPorSolicitud")
                        .HasForeignKey("SolicitudAscensoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("SolicitudAscenso");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.EvaluacionDocente", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("EvaluacionesDocentes")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.EvaluacionesPorSolicitud", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.EvaluacionDocente", "EvaluacionDocente")
                        .WithMany()
                        .HasForeignKey("EvaluacionDocenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.SolicitudAscenso", "SolicitudAscenso")
                        .WithMany("EvaluacionesPorSolicitud")
                        .HasForeignKey("SolicitudAscensoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluacionDocente");

                    b.Navigation("SolicitudAscenso");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.ExperienciaLaboral", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("ExperienciasLaborales")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany("ExperienciasLaborales")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.ExperienciaPorSolicitud", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.ExperienciaLaboral", "ExperienciaLaboral")
                        .WithMany()
                        .HasForeignKey("ExperienciaLaboralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.SolicitudAscenso", "SolicitudAscenso")
                        .WithMany("ExperienciaPorSolicitud")
                        .HasForeignKey("SolicitudAscensoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExperienciaLaboral");

                    b.Navigation("SolicitudAscenso");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Investigacion", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("Investigaciones")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.InvestigacionesPorSolicitud", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Investigacion", "Investigacion")
                        .WithMany()
                        .HasForeignKey("InvestigacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.SolicitudAscenso", "SolicitudAscenso")
                        .WithMany("InvestigacionesPorSolicitud")
                        .HasForeignKey("SolicitudAscensoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investigacion");

                    b.Navigation("SolicitudAscenso");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.SolicitudAscenso", b =>
                {
                    b.HasOne("SIGAD.Domain.Entities.Docente", "Docente")
                        .WithMany("SolicitudesAscenso")
                        .HasForeignKey("DocenteCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGAD.Domain.Entities.Rango", "RangoActual")
                        .WithMany("SolicitudesComoRangoActual")
                        .HasForeignKey("RangoActualId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SIGAD.Domain.Entities.Rango", "RangoSolicitado")
                        .WithMany("SolicitudesComoRangoSolicitado")
                        .HasForeignKey("RangoSolicitadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("RangoActual");

                    b.Navigation("RangoSolicitado");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Docente", b =>
                {
                    b.Navigation("Articulos");

                    b.Navigation("Cuenta")
                        .IsRequired();

                    b.Navigation("Cursos");

                    b.Navigation("EvaluacionesDocentes");

                    b.Navigation("ExperienciasLaborales");

                    b.Navigation("Investigaciones");

                    b.Navigation("SolicitudesAscenso");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Organizacion", b =>
                {
                    b.Navigation("Cursos");

                    b.Navigation("ExperienciasLaborales");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.Rango", b =>
                {
                    b.Navigation("SolicitudesComoRangoActual");

                    b.Navigation("SolicitudesComoRangoSolicitado");
                });

            modelBuilder.Entity("SIGAD.Domain.Entities.SolicitudAscenso", b =>
                {
                    b.Navigation("ArticulosPorSolicitud");

                    b.Navigation("CursosPorSolicitud");

                    b.Navigation("EvaluacionesPorSolicitud");

                    b.Navigation("ExperienciaPorSolicitud");

                    b.Navigation("InvestigacionesPorSolicitud");
                });
#pragma warning restore 612, 618
        }
    }
}
